### ISSUE TITLE
Add a header formatter that works similar to labelFormatter prop

### ISSUE THREAD

**Issue by basselAhmed** [apxor/react-cohort-graph#2]
This is a feature request to let the user be able to modify the table header using custom functions same as labelFormatter that already exist in the code base.

**Comment by arajajyothibabu** [comment]
Sure @basselAhmed, I think it's quite useful and let you know when it's done.

**Comment by basselAhmed** [comment]
@arajajyothibabu I could help you out with this and make a PR when it's done

**Comment by arajajyothibabu** [comment]
Thank you @basselAhmed :+1: 
https://github.com/apxor/react-cohort-graph/commit/eef1ae6663d9d45d50a8bcb7788dc78da4619bf7
