### ISSUE TITLE
It is possible parse dateDisplayFormat?

### ISSUE THREAD

**Issue by fabiorogeriosj** [apxor/react-cohort-graph#7]

**Comment by rakhi2104** [comment]
Yes, it is possible.
```
index: -1
isDate: true
isFixed: true
isHeader: false
```
Keep an eye on these props and you can format.

**Comment by arajajyothibabu** [comment]
Yes you can format date using `cellFormatter` callback. As @rakhi2104 told, use the parameters to identify the date. Closing this now, please revert for any queries.
